// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package robot.subsystems;


import robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.AnalogPotentiometer;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Solenoid;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class ElevSubSys extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private WPI_TalonSRX elevMtr;
    private DigitalInput elevUpperLmtSw;
    private DigitalInput elevLwrLntSw;
    private AnalogPotentiometer elevPotentiometer;
    private DigitalInput elevUpper1LmtSw;
    private DigitalInput elevUpper2LmtSw;
    private DigitalInput elevLwr1LmtSw;
    private DigitalInput elevLwr2LmtSw;
    private Solenoid elevValve;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public ElevSubSys() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        elevMtr = new WPI_TalonSRX(3);
        
        
        
        elevUpperLmtSw = new DigitalInput(22);
        addChild("ElevUpperLmtSw",elevUpperLmtSw);
        
        
        elevLwrLntSw = new DigitalInput(23);
        addChild("ElevLwrLntSw",elevLwrLntSw);
        
        
        elevPotentiometer = new AnalogPotentiometer(3, 5.0, 0.0);
        addChild("Elev Potentiometer",elevPotentiometer);
        
        
        elevUpper1LmtSw = new DigitalInput(6);
        addChild("ElevUpper1LmtSw",elevUpper1LmtSw);
        
        
        elevUpper2LmtSw = new DigitalInput(7);
        addChild("ElevUpper2LmtSw",elevUpper2LmtSw);
        
        
        elevLwr1LmtSw = new DigitalInput(8);
        addChild("ElevLwr1LmtSw",elevLwr1LmtSw);
        
        
        elevLwr2LmtSw = new DigitalInput(9);
        addChild("ElevLwr2LmtSw",elevLwr2LmtSw);
        
        
        elevValve = new Solenoid(0, 4);
        addChild("elevValve",elevValve);
        
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

